YMP_WEBSITE/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

core/urls.py
from django.urls import path
from core.views import register, main, groups, news, profile, logout_from
from django.contrib.auth.views import LoginView


urlpatterns = [
    # 1-путь,2-функция,3-кр.название
    path('', main, name='main'),
    path('register/', register, name='register'),
    path('groups/', groups, name='groups'),
    path('news/', news, name='news'),
    path('accounts/profile/', profile, name='profile'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', logout_from, name='logout')

]

core/models.py
from django.db import models
from django.contrib.auth.models import User

#Registration

class Student(User):
    age = models.IntegerField(null=False)
    specialization = models.CharField(max_length = 255)

    def __str__(self):
        return  self.last_name

core/forms.py
from django.forms import ModelForm
from django.forms import CharField, PasswordInput
from .models import Student


class StudentRegistrationForm(ModelForm):

    password_1 = CharField(max_length=20, min_length=6, widget=PasswordInput)
    password_2 = CharField(max_length=20, min_length=6, widget=PasswordInput)

    class Meta:
        model = Student
        fields = ( 'first_name', 'last_name', 'username', 'age')

    def check_pass(self):
        data = self.cleaned_data
        if data['password_1'] != data['password_2']:
            raise ValidationError('Неверный повтор пароля')
        return data['password_1']

core/views.py
from django.shortcuts import render
from core.forms import StudentRegistrationForm
from core.forms import Student
from django.contrib.auth.views import auth_logout

def register(request):
    if request.method == 'POST':
        user_form = StudentRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password_1'])
            new_user.save()
            return render(request, 'registration/login.html', {'new_user': new_user})
        else:
            user_form = StudentRegistrationForm()
        return render(request, 'register.html', {'user_form': user_form})
    if request.method == 'GET':
        return render(request, 'register.html')


def main(request):
    return render(request, 'main.html')



def groups(request):
    return render(request, 'groups.html')




def news(request):
    return render(request, 'news.html')



def profile(request):
    return render(request, 'profile.html')

def logout_from(request):
    print('Вышел')
    logout(request)
    return render(request, 'main.html')

templates/groups.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ВГУЭС</title>
    <link rel="stylesheet" href="{% static 'groups.css' %}">
</head>
<body>
<header>
    <div class="header">
        <div class="logo">
            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="120" height="38"
                 viewBox="0 0 120 38">
                <defs>
                    <style>
                        .cls-1 {
                            fill: #fff;
                            fill-rule: evenodd;
                            filter: url(#filter);
                        }
                    </style>
                    <filter id="filter" x="99" y="35" width="120" height="38" filterUnits="userSpaceOnUse">
                        <feOffset result="offset" dy="2" in="SourceAlpha"/>
                        <feGaussianBlur result="blur" stdDeviation="1.414"/>
                        <feFlood result="flood" flood-opacity="0.12"/>
                        <feComposite result="composite" operator="in" in2="blur"/>
                        <feBlend result="blend" in="SourceGraphic"/>
                    </filter>
                </defs>
                <path class="cls-1"
                      d="M163.331,35h9.1L164.88,57.349h-0.026l-0.593,1.756c-1.761,5.218-7.209,9.525-12.334,9.872l0,0.008h-0.138c-0.173.01-.346,0.014-0.518,0.014h-0.882c-0.173,0-.344,0-0.51-0.014h-9.138l3.338-9.88,0.056-.169h7.593a5.618,5.618,0,0,0,4.791-3.769l0.075-.218,0.257-.758H149.9c-0.935,0-4.166,0-2.8-4.03l0.955-2.824,0.818-2.427L152.22,35H160l-4.623,13.7H158.7c0.553-1.638,3.359-9.942,4.628-13.7h0Zm-19.414,0-0.011.032c-5.166.275-10.7,4.615-12.479,9.881L128.3,54.173l-1.665,4.932-3.339,9.88h9.139c0.1,0.006.2,0.01,0.3,0.013L139.6,48.684a5.767,5.767,0,0,1,4.988-3.8h1.506L149.432,35h-5.515Zm63.821,0H217l-3.342,9.891h-5.991a5.619,5.619,0,0,0-4.791,3.769l-0.074.22-2.126,6.292L199.4,58.937h11.3l-0.056.169c-1.763,5.218-7.211,9.525-12.335,9.872l0,0.008h-0.136c-0.174.01-.348,0.014-0.52,0.014h-0.883c-0.174,0-.343,0-0.509-0.014h-9.138l3.339-9.88,1.666-4.932,3.129-9.264c1.778-5.266,7.312-9.606,12.477-9.881L207.738,35h0Zm-87.115,0h10.363L126.7,47.656a5.3,5.3,0,0,1-4.13,3.769l3.572,0.019-2,5.905h-0.025l-0.592,1.756c-1.763,5.218-7.211,9.525-12.336,9.872l0,0.008H111.05c-0.174.01-.347,0.014-0.52,0.014h-0.882q-0.26,0-.51-0.014H100l3.338-9.88L105,54.173l3.13-9.264c1.779-5.266,7.312-9.606,12.478-9.881L120.623,35h0Zm-2.72,8.891c-1.023,0-2.233,1.3-2.576,2.289l-0.94,2.725h5.081l1.724-5.014H117.9Zm-5.421,10.654-1.9,5.876h3.01c1.575,0,2.637-1.634,2.878-2.362l1.162-3.515h-5.146ZM184.36,35l-0.011.032c-5.16.275-10.685,4.6-12.471,9.859h10.741l-1.274,3.769h0l-0.074.22h-8.825l-1.924,5.695h8.827l-0.129.379-0.075.218a5.62,5.62,0,0,1-4.792,3.769h-7.222l-0.056.169-3.338,9.88h9.137c0.168,0.01.337,0.014,0.509,0.014h0.884q0.258,0,.519-0.014h0.138l0-.008c5.124-.347,10.572-4.654,12.335-9.872l0.592-1.756h0.025L195.43,35H184.36Z"
                      transform="translate(-99 -35)"/>
            </svg>
        </div>
        <nav>
            <ul class="nav">
                <li>
                    <a href={% url 'main' %}>
                        Главная
                    </a>
                </li>
                <li>
                    <button class="nav_btn" type="button">
                        <a href={% url 'groups' %}>
                            Объединения
                        </a>
                    </button>
                </li>
                <li>
                    <a href={% url 'news' %}>
                        Новости
                    </a>
                </li>
                <li>
                    <a href={% url 'login' %}>
                        Профиль
                    </a>
                </li>
                <li>
                    <a href={% url 'register' %}>
                        Регистрация
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</header>
<section>
    <div class="container">
        <div class="content">
            <h1>
                Cтудия современной хореографии "Грани"
            </h1>
            Работа коллектива крайне разносторонняя, она течет в русле модерна,
            джаза, хип-хопа, эстрады и даже танцев народов мира. Свое творческое лицо,
            оригинальный авторский репертуар и своеобразная манера исполнения выгодно отличают “Грани”
            от других танцевальных коллективов.
            <br>
            Студия современной хореографии «Грани» выступает на всех известных площадках города Владивостока: ВДЦ
            «Океан»,
            «Галактика», СТКК «Андеграунд», ДК «Феско холл», ДК «Железнодорожников», Филармония,
            Дом офицеров флота, отель «Хёндай», открытая сцена на корабельной набережной, Центральная площадь и
            другие.
        </div>
        <div class="imgBx">
            <img src="../static/images/градус.jpg">
        </div>
    </div>
</section>
<section>
    <div class="container">
        <div class="content">
            <h1>
                Вокальный коллектив "Престиж" ВГУЭС
            </h1>
            Вокальный коллектив эстрадной песни был основан в 2000 году
            на базе Владивостокского государственного университета экономики и сервиса.
            Уникальность коллектива в том, что его деятельность осуществляется исключительно на творческой основе.
            Каждый учебный год несет в себе что-то новое, интересное, неповторимое.
            <br>
            Главное отличие эстрадной музыки и по сей день – это простота формы и содержания, доступность понимания
            массам.
            Эстрадное пение сочетает в себе множество песенных направлений, объединяет всю палитру вокального искусства.
        </div>
        <div class="imgBx">
            <img src="../static/images/дед%20(2).jpg">
        </div>
    </div>
</section>
</body>
</html>

templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ВГУЭС</title>
    <link rel="stylesheet" href="{% static 'mainstyle.css' %}">
</head>
<body>
<header>
    <div class="header">
        <div class="logo">
            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="120" height="38" viewBox="0 0 120 38">
  <defs>
    <style>
      .cls-1 {
        fill: #fff;
        fill-rule: evenodd;
        filter: url(#filter);
      }
    </style>
    <filter id="filter" x="99" y="35" width="120" height="38" filterUnits="userSpaceOnUse">
      <feOffset result="offset" dy="2" in="SourceAlpha"/>
      <feGaussianBlur result="blur" stdDeviation="1.414"/>
      <feFlood result="flood" flood-opacity="0.12"/>
      <feComposite result="composite" operator="in" in2="blur"/>
      <feBlend result="blend" in="SourceGraphic"/>
    </filter>
  </defs>
  <path class="cls-1" d="M163.331,35h9.1L164.88,57.349h-0.026l-0.593,1.756c-1.761,5.218-7.209,9.525-12.334,9.872l0,0.008h-0.138c-0.173.01-.346,0.014-0.518,0.014h-0.882c-0.173,0-.344,0-0.51-0.014h-9.138l3.338-9.88,0.056-.169h7.593a5.618,5.618,0,0,0,4.791-3.769l0.075-.218,0.257-.758H149.9c-0.935,0-4.166,0-2.8-4.03l0.955-2.824,0.818-2.427L152.22,35H160l-4.623,13.7H158.7c0.553-1.638,3.359-9.942,4.628-13.7h0Zm-19.414,0-0.011.032c-5.166.275-10.7,4.615-12.479,9.881L128.3,54.173l-1.665,4.932-3.339,9.88h9.139c0.1,0.006.2,0.01,0.3,0.013L139.6,48.684a5.767,5.767,0,0,1,4.988-3.8h1.506L149.432,35h-5.515Zm63.821,0H217l-3.342,9.891h-5.991a5.619,5.619,0,0,0-4.791,3.769l-0.074.22-2.126,6.292L199.4,58.937h11.3l-0.056.169c-1.763,5.218-7.211,9.525-12.335,9.872l0,0.008h-0.136c-0.174.01-.348,0.014-0.52,0.014h-0.883c-0.174,0-.343,0-0.509-0.014h-9.138l3.339-9.88,1.666-4.932,3.129-9.264c1.778-5.266,7.312-9.606,12.477-9.881L207.738,35h0Zm-87.115,0h10.363L126.7,47.656a5.3,5.3,0,0,1-4.13,3.769l3.572,0.019-2,5.905h-0.025l-0.592,1.756c-1.763,5.218-7.211,9.525-12.336,9.872l0,0.008H111.05c-0.174.01-.347,0.014-0.52,0.014h-0.882q-0.26,0-.51-0.014H100l3.338-9.88L105,54.173l3.13-9.264c1.779-5.266,7.312-9.606,12.478-9.881L120.623,35h0Zm-2.72,8.891c-1.023,0-2.233,1.3-2.576,2.289l-0.94,2.725h5.081l1.724-5.014H117.9Zm-5.421,10.654-1.9,5.876h3.01c1.575,0,2.637-1.634,2.878-2.362l1.162-3.515h-5.146ZM184.36,35l-0.011.032c-5.16.275-10.685,4.6-12.471,9.859h10.741l-1.274,3.769h0l-0.074.22h-8.825l-1.924,5.695h8.827l-0.129.379-0.075.218a5.62,5.62,0,0,1-4.792,3.769h-7.222l-0.056.169-3.338,9.88h9.137c0.168,0.01.337,0.014,0.509,0.014h0.884q0.258,0,.519-0.014h0.138l0-.008c5.124-.347,10.572-4.654,12.335-9.872l0.592-1.756h0.025L195.43,35H184.36Z" transform="translate(-99 -35)"/>
</svg>
        </div>
        <nav>
            <ul class="nav">
                <li>
                    <button class="nav_btn" type="button">
                        <a href={% url 'main' %}>
                                Главная
                        </a>
                    </button>
                </li>
                <li>
                    <a href={% url 'groups' %}>
                            Объединения
                    </a>
                </li>
                <li>
                    <a href={% url 'news' %}>
                            Новости
                    </a>
                </li>

                <li>
                    <a href={% url 'login' %}>
                           Профиль
                    </a>
                </li>
                <li>
                    <a href={% url 'register' %}>
                            Регистрация
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</header>
{% block main %}

{% endblock %}
</body>
</html>

templates/news.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ВГУЭС</title>
    <link rel="stylesheet" href="{% static 'news.css' %}">
</head>
<body>
<header>
    <div class="header">
        <div class="logo">
            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="120" height="38" viewBox="0 0 120 38">
  <defs>
    <style>
      .cls-1 {
        fill: #fff;
        fill-rule: evenodd;
        filter: url(#filter);
      }
    </style>
    <filter id="filter" x="99" y="35" width="120" height="38" filterUnits="userSpaceOnUse">
      <feOffset result="offset" dy="2" in="SourceAlpha"/>
      <feGaussianBlur result="blur" stdDeviation="1.414"/>
      <feFlood result="flood" flood-opacity="0.12"/>
      <feComposite result="composite" operator="in" in2="blur"/>
      <feBlend result="blend" in="SourceGraphic"/>
    </filter>
  </defs>
  <path class="cls-1" d="M163.331,35h9.1L164.88,57.349h-0.026l-0.593,1.756c-1.761,5.218-7.209,9.525-12.334,9.872l0,0.008h-0.138c-0.173.01-.346,0.014-0.518,0.014h-0.882c-0.173,0-.344,0-0.51-0.014h-9.138l3.338-9.88,0.056-.169h7.593a5.618,5.618,0,0,0,4.791-3.769l0.075-.218,0.257-.758H149.9c-0.935,0-4.166,0-2.8-4.03l0.955-2.824,0.818-2.427L152.22,35H160l-4.623,13.7H158.7c0.553-1.638,3.359-9.942,4.628-13.7h0Zm-19.414,0-0.011.032c-5.166.275-10.7,4.615-12.479,9.881L128.3,54.173l-1.665,4.932-3.339,9.88h9.139c0.1,0.006.2,0.01,0.3,0.013L139.6,48.684a5.767,5.767,0,0,1,4.988-3.8h1.506L149.432,35h-5.515Zm63.821,0H217l-3.342,9.891h-5.991a5.619,5.619,0,0,0-4.791,3.769l-0.074.22-2.126,6.292L199.4,58.937h11.3l-0.056.169c-1.763,5.218-7.211,9.525-12.335,9.872l0,0.008h-0.136c-0.174.01-.348,0.014-0.52,0.014h-0.883c-0.174,0-.343,0-0.509-0.014h-9.138l3.339-9.88,1.666-4.932,3.129-9.264c1.778-5.266,7.312-9.606,12.477-9.881L207.738,35h0Zm-87.115,0h10.363L126.7,47.656a5.3,5.3,0,0,1-4.13,3.769l3.572,0.019-2,5.905h-0.025l-0.592,1.756c-1.763,5.218-7.211,9.525-12.336,9.872l0,0.008H111.05c-0.174.01-.347,0.014-0.52,0.014h-0.882q-0.26,0-.51-0.014H100l3.338-9.88L105,54.173l3.13-9.264c1.779-5.266,7.312-9.606,12.478-9.881L120.623,35h0Zm-2.72,8.891c-1.023,0-2.233,1.3-2.576,2.289l-0.94,2.725h5.081l1.724-5.014H117.9Zm-5.421,10.654-1.9,5.876h3.01c1.575,0,2.637-1.634,2.878-2.362l1.162-3.515h-5.146ZM184.36,35l-0.011.032c-5.16.275-10.685,4.6-12.471,9.859h10.741l-1.274,3.769h0l-0.074.22h-8.825l-1.924,5.695h8.827l-0.129.379-0.075.218a5.62,5.62,0,0,1-4.792,3.769h-7.222l-0.056.169-3.338,9.88h9.137c0.168,0.01.337,0.014,0.509,0.014h0.884q0.258,0,.519-0.014h0.138l0-.008c5.124-.347,10.572-4.654,12.335-9.872l0.592-1.756h0.025L195.43,35H184.36Z" transform="translate(-99 -35)"/>
</svg>
        </div>
        <nav>
            <ul class="nav">
                <li>
                    <a href={% url 'main' %}>
                        Главная
                    </a>
                </li>
                <li>
                    <a href={% url 'groups' %}>
                        Объединения
                    </a>
                </li>
                <li>
                    <button class="nav_btn" type="button">
                        <a href={% url 'news' %}>
                            Новости
                        </a>
                    </button>
                </li>
                <li>
                    <a href={% url 'login' %}>
                        Профиль
                    </a>
                </li>
                <li>
                    <a href={% url 'register' %}>
                        Регистрация
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</header>
</body>
</html>

templates/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ВГУЭС</title>
    <link rel="stylesheet" href="{% static 'profile.css' %}">
</head>
<body>
<header>
    <div class="header">
        <div class="logo">
            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="120" height="38" viewBox="0 0 120 38">
  <defs>
    <style>
      .cls-1 {
        fill: #fff;
        fill-rule: evenodd;
        filter: url(#filter);
      }
    </style>
    <filter id="filter" x="99" y="35" width="120" height="38" filterUnits="userSpaceOnUse">
      <feOffset result="offset" dy="2" in="SourceAlpha"/>
      <feGaussianBlur result="blur" stdDeviation="1.414"/>
      <feFlood result="flood" flood-opacity="0.12"/>
      <feComposite result="composite" operator="in" in2="blur"/>
      <feBlend result="blend" in="SourceGraphic"/>
    </filter>
  </defs>
  <path class="cls-1" d="M163.331,35h9.1L164.88,57.349h-0.026l-0.593,1.756c-1.761,5.218-7.209,9.525-12.334,9.872l0,0.008h-0.138c-0.173.01-.346,0.014-0.518,0.014h-0.882c-0.173,0-.344,0-0.51-0.014h-9.138l3.338-9.88,0.056-.169h7.593a5.618,5.618,0,0,0,4.791-3.769l0.075-.218,0.257-.758H149.9c-0.935,0-4.166,0-2.8-4.03l0.955-2.824,0.818-2.427L152.22,35H160l-4.623,13.7H158.7c0.553-1.638,3.359-9.942,4.628-13.7h0Zm-19.414,0-0.011.032c-5.166.275-10.7,4.615-12.479,9.881L128.3,54.173l-1.665,4.932-3.339,9.88h9.139c0.1,0.006.2,0.01,0.3,0.013L139.6,48.684a5.767,5.767,0,0,1,4.988-3.8h1.506L149.432,35h-5.515Zm63.821,0H217l-3.342,9.891h-5.991a5.619,5.619,0,0,0-4.791,3.769l-0.074.22-2.126,6.292L199.4,58.937h11.3l-0.056.169c-1.763,5.218-7.211,9.525-12.335,9.872l0,0.008h-0.136c-0.174.01-.348,0.014-0.52,0.014h-0.883c-0.174,0-.343,0-0.509-0.014h-9.138l3.339-9.88,1.666-4.932,3.129-9.264c1.778-5.266,7.312-9.606,12.477-9.881L207.738,35h0Zm-87.115,0h10.363L126.7,47.656a5.3,5.3,0,0,1-4.13,3.769l3.572,0.019-2,5.905h-0.025l-0.592,1.756c-1.763,5.218-7.211,9.525-12.336,9.872l0,0.008H111.05c-0.174.01-.347,0.014-0.52,0.014h-0.882q-0.26,0-.51-0.014H100l3.338-9.88L105,54.173l3.13-9.264c1.779-5.266,7.312-9.606,12.478-9.881L120.623,35h0Zm-2.72,8.891c-1.023,0-2.233,1.3-2.576,2.289l-0.94,2.725h5.081l1.724-5.014H117.9Zm-5.421,10.654-1.9,5.876h3.01c1.575,0,2.637-1.634,2.878-2.362l1.162-3.515h-5.146ZM184.36,35l-0.011.032c-5.16.275-10.685,4.6-12.471,9.859h10.741l-1.274,3.769h0l-0.074.22h-8.825l-1.924,5.695h8.827l-0.129.379-0.075.218a5.62,5.62,0,0,1-4.792,3.769h-7.222l-0.056.169-3.338,9.88h9.137c0.168,0.01.337,0.014,0.509,0.014h0.884q0.258,0,.519-0.014h0.138l0-.008c5.124-.347,10.572-4.654,12.335-9.872l0.592-1.756h0.025L195.43,35H184.36Z" transform="translate(-99 -35)"/>
</svg>
        </div>
        <nav>
            <ul class="nav">
                <li>
                    <a href={% url 'main' %}>
                        Главная
                    </a>
                </li>
                <li>
                    <a href={% url 'groups' %}>
                        Объединения
                    </a>
                </li>
                <li>
                    <a href={% url 'news' %}>
                        Новости
                    </a>
                </li>
                <li>
                    <button class="nav_btn" type="button">
                        <a href={% url 'login' %}>
                            Профиль
                        </a>
                    </button>
                </li>
                <li>
                    <a href={% url 'register' %}>
                        Регистрация
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</header>
</body>
</html>

templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ВГУЭС</title>
    <link rel="stylesheet" href="{% static 'register.css' %}">
</head>
<body>
<header>
    <div class="header">
        <div class="logo">
            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="120" height="38" viewBox="0 0 120 38">
  <defs>
    <style>
      .cls-1 {
        fill: #fff;
        fill-rule: evenodd;
        filter: url(#filter);
      }
    </style>
    <filter id="filter" x="99" y="35" width="120" height="38" filterUnits="userSpaceOnUse">
      <feOffset result="offset" dy="2" in="SourceAlpha"/>
      <feGaussianBlur result="blur" stdDeviation="1.414"/>
      <feFlood result="flood" flood-opacity="0.12"/>
      <feComposite result="composite" operator="in" in2="blur"/>
      <feBlend result="blend" in="SourceGraphic"/>
    </filter>
  </defs>
  <path class="cls-1" d="M163.331,35h9.1L164.88,57.349h-0.026l-0.593,1.756c-1.761,5.218-7.209,9.525-12.334,9.872l0,0.008h-0.138c-0.173.01-.346,0.014-0.518,0.014h-0.882c-0.173,0-.344,0-0.51-0.014h-9.138l3.338-9.88,0.056-.169h7.593a5.618,5.618,0,0,0,4.791-3.769l0.075-.218,0.257-.758H149.9c-0.935,0-4.166,0-2.8-4.03l0.955-2.824,0.818-2.427L152.22,35H160l-4.623,13.7H158.7c0.553-1.638,3.359-9.942,4.628-13.7h0Zm-19.414,0-0.011.032c-5.166.275-10.7,4.615-12.479,9.881L128.3,54.173l-1.665,4.932-3.339,9.88h9.139c0.1,0.006.2,0.01,0.3,0.013L139.6,48.684a5.767,5.767,0,0,1,4.988-3.8h1.506L149.432,35h-5.515Zm63.821,0H217l-3.342,9.891h-5.991a5.619,5.619,0,0,0-4.791,3.769l-0.074.22-2.126,6.292L199.4,58.937h11.3l-0.056.169c-1.763,5.218-7.211,9.525-12.335,9.872l0,0.008h-0.136c-0.174.01-.348,0.014-0.52,0.014h-0.883c-0.174,0-.343,0-0.509-0.014h-9.138l3.339-9.88,1.666-4.932,3.129-9.264c1.778-5.266,7.312-9.606,12.477-9.881L207.738,35h0Zm-87.115,0h10.363L126.7,47.656a5.3,5.3,0,0,1-4.13,3.769l3.572,0.019-2,5.905h-0.025l-0.592,1.756c-1.763,5.218-7.211,9.525-12.336,9.872l0,0.008H111.05c-0.174.01-.347,0.014-0.52,0.014h-0.882q-0.26,0-.51-0.014H100l3.338-9.88L105,54.173l3.13-9.264c1.779-5.266,7.312-9.606,12.478-9.881L120.623,35h0Zm-2.72,8.891c-1.023,0-2.233,1.3-2.576,2.289l-0.94,2.725h5.081l1.724-5.014H117.9Zm-5.421,10.654-1.9,5.876h3.01c1.575,0,2.637-1.634,2.878-2.362l1.162-3.515h-5.146ZM184.36,35l-0.011.032c-5.16.275-10.685,4.6-12.471,9.859h10.741l-1.274,3.769h0l-0.074.22h-8.825l-1.924,5.695h8.827l-0.129.379-0.075.218a5.62,5.62,0,0,1-4.792,3.769h-7.222l-0.056.169-3.338,9.88h9.137c0.168,0.01.337,0.014,0.509,0.014h0.884q0.258,0,.519-0.014h0.138l0-.008c5.124-.347,10.572-4.654,12.335-9.872l0.592-1.756h0.025L195.43,35H184.36Z" transform="translate(-99 -35)"/>
</svg>
        </div>
        <nav>
            <ul class="nav">
                <li>
                    <a href={% url 'main' %}>
                        Главная
                    </a>
                </li>
                <li>
                    <a href={% url 'groups' %}>
                        Объединения
                    </a>
                </li>
                <li>
                    <a href={% url 'news' %}>
                        Новости
                    </a>
                </li>
                <li>
                    <a href={% url 'login' %}>
                        Профиль
                    </a>
                </li>
                <li>
                    <button class="nav_btn" type="button">
                        <a href={% url 'register' %}>
                            Регистрация
                        </a>
                    </button>
                </li>
            </ul>
        </nav>
    </div>
</header>




    <div class="card_register">
        <div class="card-body">
            <h4 class="card-title">Register account</h4>
            <form method="post">
                {% csrf_token %}
                <div class="reg_form_view">

                    <p><input class="input_1" type="text" name="last_name" maxlength="150" id="id_last_name" placeholder="Фамилия"></p>
                    <p><input class="input_1"  type="text" name="first_name" maxlength="150" id="id_first_name" placeholder="Имя"></p>
                    <p><input class="input_1" type="number" name="age" required="" id="id_age" placeholder="Возраст"></p>
                    <p><input class="input_1" type="text" name="username" maxlength="254"
                           id="id_email" placeholder="username"></p>
                    <p><input class="input_1" type="text" name="specialization" maxlength="150" required="" id="id_specialization" placeholder="Специализация"></p>
                   <p> <input class="input_1" type="password" name="password_1" maxlength="20"
                           minlength="6" required="" id="id_password_1" placeholder="Пароль"></p>
                   <p> <input class="input_1" type="password" name="password_2" maxlength="20"
                           minlength="6" required="" id="id_password_2" placeholder="Подтвердите пароль"></p>

                    <div class="form-group g-recaptcha" data-sitekey="6LfBMSgcAAAAAFq5Ctxc2Ep8K1STmdfBaP6ZFbfY"></div>
                    <input type="submit" class="btn-log" value="Register">
                    {% if messages %}
                        {% for message in messages %}
                            {{ message }}
                        {% endfor %}
                    {% endif %}
                </div>
            </form>
        </div>
    </div>
</body>
</html>